// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {courantHighlighting} from "./highlight"
const spec_Identifier = {__proto__:null,true:16, false:16, raise:24, not:36, and:46, or:48, return:56, if:66, else:68, while:72, throw:76, try:80, catch:82}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*OQYQPOOOOQO'#Cc'#CcO#RQPO'#CvO#YQPO'#CkO#tQPO'#D^OOQO'#D^'#D^O#YQPO'#D^O$uQPO'#CyOOQO'#D]'#D]OOQO'#DW'#DWQYQPOOO$|QPO'#CgO#YQPO'#CwO%RQPO'#C|O%WQPO'#DPO#YQPO'#DROYQPO'#DTO%]QPO,59TOOQO'#Cr'#CrO#YQPO,59ZO#YQPO,59ZO#YQPO,59ZOOQO,59b,59bO#YQPO,59ZO%dQPO,59VO#YQPO,58yO%qQPO,59xOOQO,59e,59eO%xQPO,59eOOQO-E7U-E7UO#YQPO,59RO&PQPO,59cO#YQPO,59hO#YQPO,59kO&WQPO,59mO&_QPO,59oO&dQPO1G.oOOQO1G.o1G.oO'lQPO1G.uO'vQPO1G.uO(rQPO1G.uO)YQPO1G.uO)pQPO1G.eOOQO1G/d1G/dOOQO1G/P1G/PO)wQPO1G.mOOQO1G.}1G.}O*OQPO1G/SO*VQPO1G/VOOQO1G/X1G/XO*^QPO1G/ZO#YQPO'#DXO*cQPO7+$ZOOQO7+$Z7+$ZOOQO7+$P7+$POOQO7+$X7+$XOYQPO7+$nOYQPO7+$qO*kQPO7+$uO*pQPO,59sOOQO-E7V-E7VOOQO<<Gu<<GuO*zQPO<<HYOOQO<<H]<<H]O,UQPO<<HaOYQPOAN=tOYQPOAN={OOQOG23`G23`OOQOG23gG23g",
  stateData: ",Z~O!OOSPOS~OSSOUTOWPOXUO[ZO`ROaRObROl[OnVOq]Ot^Ov_Ox`O~OXaO`dOadOdcOecOggOhgO!RbO!SbO!TbO!UbO!VbO!WbO~OifO~P!WOSTOUTOWPOXUO[ZO`ROaRObRO~OTiOX!QX`!QXa!QXd!QXe!QXg!QXh!QXi!QX!R!QX!S!QX!T!QX!U!QX!V!QX!W!QX~OokO~PYOXnO~OXpO~OXqO~OYuO~P#YOi_aY_a^_a~P!WOY{O~P!WOo|O~PYOi!OO~P!WOi!RO~P!WOy!SO~OY!VO^!TO~P!WOXaO`ciacigcihciici!Rci!Sci!Tci!Uci!Vci!WciYci^ci~Odcieci~P&nOdcOecO~P&nOXaO`dOadOdcOecOgcihciiciYci^ci~O!Rci!Sci!Tci!Uci!Vci!Wci~P(QO!RbO!SbO!TbO!UbO!VbO!WbO~P(QOi!WO~P!WOY!XO~P!WOY!YO~P!WOY!ZO~P!WOX![O~OY!_O^!TO~OS!bO~OY{a^{a~P!WOr!cOSpyUpyWpyXpy[py`pyapybpylpynpyqpytpyvpyxpy|pyopyypy~OY!dO~O",
  goto: "%U!RPPP!SPPP!_PPP!_P!_P!_PPP!_PP!xPPP!S!SP!SPP!SPP!SP!SP!SPP#W#bPPP#h#}cWOVY`l!Y!Z!c!d!PTORUVY[_`acdegilnpq!T!Y!Z!c!dieQhjortyz}!P!Q!]QYOQlVTmYlQ!UtR!^!UWXOVYlQs`Q!`!YQ!a!ZQ!e!cR!f!dbQOVY`l!Y!Z!c!dQhRQjUQo[Qr_QtaQvcQwdQxeQygQziQ}nQ!PpQ!QqR!]!T",
  nodeNames: "⚠ LineComment Program AssignStmt Identifier = Number Boolean Boolean ( ) RaiseExpr raise FunctionCall , UnaryExpr Plus Minus not BinaryExpr Mul Div CompareOp and or ; ExprStmt ReturnStmt return BlockStmt { } IfStmt if else WhileStmt while ThrowStmt throw TryCatchStmt try catch",
  maxTerm: 54,
  propSources: [courantHighlighting],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "&b~RgXY!jYZ!j]^!jpq!jqr!{st#Wxy#oyz#tz{#y{|$O|}$T}!O$Y!P!Q$_!Q![$d!]!^$w!^!_$|!_!`%Z!`!a%h!c!}%u#R#S%u#T#o%u#o#p&W#q#r&]~!oS!O~XY!jYZ!j]^!jpq!j~#OP!_!`#R~#WO!U~~#]SP~OY#WZ;'S#W;'S;=`#i<%lO#W~#lP;=`<%l#W~#tOX~~#yOY~~$OOd~~$TO`~~$YO^~~$_Oa~~$dOe~~$iQU~!O!P$o!Q![$d~$tPU~!Q![$o~$|Oi~~%RP!R~!_!`%U~%ZO!S~~%`PT~!_!`%c~%hO!T~~%mP!V~!_!`%p~%uO!W~~%zSS~!Q![%u!c!}%u#R#S%u#T#o%u~&]On~~&bOo~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 4, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
